name: flutter_form_wizard
description: A new Flutter package project.
version: 6.3.2
homepage: https://github.com/Iconica-Development/flutter_form_wizard

publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ">=0.18.0 <1.0.0"
  flutter_input_library:
    git:
      url: https://github.com/Iconica-Development/flutter_input_library
      ref: 3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter:
